apiVersion: v1
data:
  QUOTES_DATABASE: aXRlbXM=
  QUOTES_ROOT_PASSWORD: cjAwdHBhNTU=
  QUOTES_USER: dXNlcjE=
  QUOTES_hostname: bXlzcWw=
  QUOTES_password: bXlwYTU1
kind: Secret
metadata:
  name: quotes
